POST http://localhost:5287/api/habit
Content-Type: application/json

{
    "name": "Take vitamins"
}

###

GET http://localhost:5287/api/habit

###

POST http://localhost:5287/api/habit/1/complete

###

DELETE http://localhost:5287/api/habit/1
